/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AccountHandler;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Primax
 */
public class DeleteAccView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListAccountByNameView
     */
    private DefaultTableModel dtm;
    private int row = -1;
    public javax.swing.JDesktopPane dskPane;
    AccountHandler ach;
    
    public void refereshTable(){
        dtm.setRowCount(0);
        ArrayList<Object[]> data = ach.searchNameForTable(txtName.getText());
        
        for(Object obj[] : data){
            dtm.addRow(obj);
        }
    }
    
    public DeleteAccView(javax.swing.JDesktopPane dskPane) {
        this.dskPane = dskPane;
        initComponents();
        btnDelete.setEnabled(false);
        ach = new AccountHandler();
        dtm = (DefaultTableModel) tblListAccounts.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListAccounts = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("List Accounts by Name");

        jLabel1.setText("Account Holder's Name:");

        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        tblListAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Account Number", "Name", "Mobile Number", "Amount", "Account Type"
            }
        ));
        tblListAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListAccountsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListAccounts);

        btnDelete.setText("Delete Selected Account");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch))
                            .addComponent(btnDelete))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        refereshTable();
        
    }//GEN-LAST:event_btnSearchMouseClicked

    private void tblListAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListAccountsMouseClicked
        // TODO add your handling code here:
        this.row = tblListAccounts.getSelectedRow();
        if(this.row >= 0){
            btnDelete.setEnabled(true);
        }
        
    }//GEN-LAST:event_tblListAccountsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(row<0){
            JOptionPane.showMessageDialog(dskPane, "Please select at leaset one result.");
            return;
        }
        if(ach.deleteAccount(ach.search(Long.parseLong(tblListAccounts.getValueAt(row,0).toString())))){
            JOptionPane.showMessageDialog(dskPane, "Account Deleted Successfully.");
        }
        else{
             JOptionPane.showMessageDialog(dskPane, "Account cannot be deleted.");
        }
        row = -1;
        btnDelete.setEnabled(false);
        refereshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListAccounts;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
